# Generated by Django 4.2.1 on 2023-05-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mediafiles')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('caption', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2500)),
                ('tags', models.CharField(max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Posts.postimage')),
            ],
        ),
    ]
