# Generated by Django 4.2.1 on 2023-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_posts_postimage_alter_posts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='postimage',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mediafiles'),
        ),
        migrations.DeleteModel(
            name='Postimage',
        ),
    ]
